# This script creates impairment data for the 2020 EBA exposure data in the same format as for the 2016 data. In this
# way we can use the data doing the same computation with the set of functions provided by the package. The data
# are generated by using estimates from the paper "Rules of Thumb for Bank Solvency Stress Tests" by Daniel Hardy and
# Christian Schmiederer, IMF Working Paper 13/232. The specific values are based on their table 2. The script can only
# be run once eba_exposures_2020 is generated by running the make_balance_sheets_2020 has been run.

# loading the necessary packages

library(readr)
library(tibble)
library(dplyr)
library(tidyr)

# We build the basic dataframe. We need repeat the whole frame once because one frame will record the baseline scenario
# and the other frame the stress scenario in one year.

data <- eba_exposures_2020

base_frame_1 <- data %>%
  select(LEI_code, Country_code, Bank_name, Period, Country, Exposure) %>%
  filter(!(.data$Exposure %in% c("Common tier1 equity capital", "Total assets"))) %>%
  mutate(Period = 202012) %>%
  slice(rep(dplyr::row_number(), 2))

base_frame_2 <- base_frame_1 %>%
  mutate(Period = 202112)

base_frame_3 <- base_frame_1 %>%
  mutate(Period = 202212)

# Create scenario columns and value columns for impairment rates.

Scen <- c(rep("Baseline scenario", dim(base_frame_1)[1] / 2), rep("Adverse scenario", dim(base_frame_1)[1] / 2))

# Numbers based on Table 2 in Hardy and Schmiederer and under the assumption that the impact of the covid recession
# will be severe in 2021, extreme in 2022 and moderate in 2023. The baseline is assumed to follow the normal scenario.

imp_2021 <- c(rep(0.003, dim(base_frame_1)[1] / 2), rep(0.024, dim(base_frame_1)[1] / 2))
imp_2022 <- c(rep(0.003, dim(base_frame_1)[1] / 2), rep(0.043, dim(base_frame_1)[1] / 2))
imp_2023 <- c(rep(0.003, dim(base_frame_1)[1] / 2), rep(0.011, dim(base_frame_1)[1] / 2))

# add to the component frames:

data_2021 <- base_frame_1 %>%
  add_column(Scenario = Scen, .after = "Period") %>%
  add_column(Impairment_rate = imp_2021)

data_2022 <- base_frame_2 %>%
  add_column(Scenario = Scen, .after = "Period") %>%
  add_column(Impairment_rate = imp_2022)

data_2023 <- base_frame_3 %>%
  add_column(Scenario = Scen, .after = "Period") %>%
  add_column(Impairment_rate = imp_2023)

# complete the dataframe

eba_impairments_2020 <- bind_rows(data_2021, data_2022, data_2023)

# write the dataframe to a file and save in the /data folder

usethis::use_data(eba_impairments_2020, overwrite = TRUE)
